### ISSUE TITLE
What is the license

### ISSUE THREAD

**Issue by stklik** [se2p/tool-competition-av#116]
Which license is valid, in the repo there are two files, one says MIT license the other one says GPL3. Could you clarify?

**Comment by p1ndsvin** [comment]
[self_driving](https://github.com/se2p/tool-competition-av/tree/main/self_driving) sub-folder has a special MIT license from the [DeepJanus tool](https://github.com/testingautomated-usi/deepjanus/blob/master/LICENSE) as the code within that folder originally belongs to that project. The GPL3 license applies to the remaining of the code base.

There was a third wrong license file (belonging to another tool) that we removed thanks to your issue.

Thanks!
