### ISSUE TITLE
Comments/suggestions on the whole repository structure

### ISSUE THREAD

**Issue by spanichella** [se2p/tool-competition-av#13]
0) I would refactor the current README.md. Specifically, let's separate the description of the repository from the actual information concerning the installation of the pipeline to run the competition. We should transform the first page to its essential information and links, see the following suggestions for it.
We need to have on the main page information like
 - what the competition is about
 - little overview on BeamNG research and make it clear we are using their simulators (with some reasoning about it)
- add if possible video of the simulation (from youtube there are many) potential scenarios
 - what we make available
- where to find the code and the guideline to run the competition 

1) before going to the low level of detail, we should cross-reference the SBST web page:
    - add the image and text concerning the competition on CPS
    - add the like to the original web page of the SBST tool competition:https://sbst21.github.io/tools/
- We should have a table of content in Markdown style (since the repository is growing) as here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2) if possible I would refactor the repository into folders
- "code-pipeline": containing the code to run the actual competition (partially described in the main page)
- OPTIONAL folder "previous results":  reference to previous paper and tools that used the previous version of the pipeline
- "datasets": previous and current dataset (if any are provided)

3) for each folder mentioned in point 2) add a low-level README.md file that describes its content.

~~4) Maybe link to the chair for the SBST tool competition somewhere, with links to home pages?~~

6) I would use a different structure for the README.md of the GUIDELINE similar to the following:

"Setup Guide and Program Description"
The goal of this part is to give a brief description of how the competition code works.

Supported Operating Systems
* Windows ..."

Pre-Requisites
* Python ...
* Memory: XX GB
...
* For usage on Windows, add ...

Setup Information
For information about setup and use, please refer to the instruction provided here.

Pipeline architecture description
...

Pipeline installation
...

TO RUN THE TOOL
....
...
"

for the architecture description, with Alessio, we got a figure from the BeamNG team for a paper we wrote with them.

7) Add section reference, so that the original pipeline is linked to the repository

8) Let's add a separate section to the "Competition Evaluation Methodology" (or something similar) to describe what the competition actually does

9) Move installation consideration under the installation  section of the pipeline

10) In general, try to have a README.md file for each sub-folder, so that who visit the repository does not get lost.

**Comment by p1ndsvin** [comment]
Main page information done

**Comment by p1ndsvin** [comment]
README on sample generators done with @alessiogambi

**Comment by alessiogambi** [comment]
Added link to SBST and SBST Competition

**Comment by p1ndsvin** [comment]
Updated guidelines. Review needed @spanichella

**Comment by spanichella** [comment]
The documentation of the competition is of high quality, as for the traditional competition, @p1ndsvin , @alessiogambi !
