### ISSUE TITLE
Test Oracles

### ISSUE THREAD

**Issue by alessiogambi** [se2p/tool-competition-av#2]
We need to define basic test oracles:
- Stand still oracle. If the car does not move in 10 sec test fail. 
- OBE (approx). We consider the position of the car (not the bounding boxes), and if this is outside the lane, triggers the test failure.
- Overall timeout. The test must complex in 5 minutes (configurable).

**Comment by p1ndsvin** [comment]
I implemented the overall timeout [3] as number of simulation steps (configurable).
See [documentation](https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGpy.step)

**Comment by alessiogambi** [comment]
fixed by b07e16fe4f9eedc3c83b44157db9b671c6f9e566 and 9d321a75e35c7091a471caef0e40b0683c940d9b
