### ISSUE TITLE
Test Validators

### ISSUE THREAD

**Issue by alessiogambi** [se2p/tool-competition-av#3]
Implement the listed test validators including:
- min road length
- max number points
- min curvature / road shapes
- self-intersection and overlapping
- "Type" checking. The test must be a list of tuples or similar. Not sure how to handle duck typing.

**Comment by p1ndsvin** [comment]
Implemented self-intersection, list of lists type checking. Also a validator that checks whether the road is inside the map was implemented.

**Comment by alessiogambi** [comment]
Great. Thanks!

**Comment by alessiogambi** [comment]
Some shapes are not possible, because BeamNG cannot handle roads where many points are too close to each other. Maybe we can use an heuristic, otherwise, the final validation is the ability of the simulator to run the tests. If it cannot, the tests are not valid.

**Comment by alessiogambi** [comment]
We might need to implement some additional validation logic (min road curvature), but for the moment we can close this, and ac4fd7f1837906c5d4bc3a8d6e6b04decf0fc15d takes care of the error logic
