### ISSUE TITLE
"oob_distance" is NaN

### ISSUE THREAD

**Issue by ezecastellano** [se2p/tool-competition-av#45]
In the current [version](https://github.com/se2p/tool-competition-av/commit/e57e159670e697d4454c5c486f30aa1d6b27ef0e), we are always obtaining NaN as the "oob_distance" value in the JSON files. 

Example: `"steering": 44.62020603589313, "steering_input": -0.08308082203328948, "brake": 0, "brake_input": 0, "throttle": 0, "throttle_input": 0, "wheelspeed": 9.729266273285269, "vel_kmh": 35, "is_oob": false, "oob_counter": 0, "max_oob_percentage": 0, "oob_distance": NaN`

After inspecting the code, we realized that in line 30 of [oob_monitor.py](https://github.com/se2p/tool-competition-av/blob/main/self_driving/oob_monitor.py) the clauses of the inline if seem to be flipped. 

Currently:
`last_max_oob_percentage = self.last_max_oob_percentage if oob_bb else float("nan") ` (line 29)
`oob_distance = float("nan") if oob_bb else self.oob_distance( wrt=wrt) `  (line 30)

How we believe it should be:
`last_max_oob_percentage = self.last_max_oob_percentage if oob_bb else float("nan") ` (line 29)
`oob_distance = self.oob_distance( wrt=wrt) if oob_bb else float("nan")` (line 30)

Could you confirm that our understanding is correct and fix the code in the repository? 
Besides, can we understand a negative value of oob_distance means that the car is out of bound and the test failed?

Thank you very much in advance, and happy new year!

**Comment by p1ndsvin** [comment]
Thanks @ezecastellano for the clear explanation and the proposed solution.

> Could you confirm that our understanding is correct and fix the code in the repository?

Your understanding is correct, oob_distance reports the distance of the center of mass of the car from the closest lane margin line, i.e. the yellow center line or the right white line.

> Can we understand a negative value of oob_distance means that the car is out of bound and the test failed?

A negative oob distance indicates you that the center of mass of the car is outside the lane. Instead, the method oob_percentage at line 45 provides information on how much a car is out of the lane.

We wish you an happy new year!
