### ISSUE TITLE
time.time_ns() method not available in Python 3.6

### ISSUE THREAD

**Issue by mrksbrg** [se2p/tool-competition-av#47]
I just tried to follow the installation guide that recommends Python 3.6 (at least it states that stuff was tested with 3.6).

The time.time_ns() method on line 120 in competition.py was introduced in Python 3.7. This has to replaced by either int(round(time.time() * 1e9)) or the docs should not recommend Python 3.6.

**Comment by alessiogambi** [comment]
@mrksbrg Thanks for pointing this out. I update the documentation to *not* recommend  Python 3.6.
