### ISSUE TITLE
BeamNG not starting, need configurable userpath

### ISSUE THREAD

**Issue by mrksbrg** [se2p/tool-competition-av#48]
BeamNG does not start with my non-standard userpath (Windows' "My Documents" moved from standard C: drive to F:). This results in a timeout when running the competition scripts.

```
2021-01-11 14:23:39,040 ERROR    Uncaught exception:
Traceback (most recent call last):
  File "road_definition.py", line 50, in <module>
    main()
  File "road_definition.py", line 39, in main
    bng = beamng.open(launch=True)
  File "F:\Anaconda3\envs\sbst21\lib\site-packages\beamngpy\beamng.py", line 318, in open
    self.skt, addr = self.server.accept()
  File "F:\Anaconda3\envs\sbst21\lib\socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out
2021-01-11 14:23:39,109 WARNING  sys:1: ResourceWarning: unclosed <socket.socket fd=696, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 64256)>

2021-01-11 14:23:39,131 WARNING  F:\Anaconda3\envs\sbst21\lib\subprocess.py:786: ResourceWarning: subprocess 11936 is still running
  ResourceWarning, source=self)
```

**Comment by alessiogambi** [comment]
The issue seems to be related to the fact that there's a **space** in the path, I updated the documentation to double-check and avoid situations like that, while we (or BeamNG) find a better solution.

**Comment by mrksbrg** [comment]
Tried copying the stuff in the default user path to F:\temp\bemang (without white spaces in the path. Got this:

![bild](https://user-images.githubusercontent.com/5861909/104196159-bf007980-5423-11eb-80cf-fcf3d8ccc6c9.png)

BeamNG appears to still work with two different userpaths at the same time.

**Comment by mrksbrg** [comment]
Installing BeamNG created files in Users\<name>\Documents\BeamNG.research on drive F: (as specified in the OS). However, when running BeamNG the tool looks for the key in the default userpath on the C: drive (C:\Users\<name>\Documents\BeamNG.research as shown in the screenshot above)

**Comment by mrksbrg** [comment]
Tried copying the license file to the new directory F:\temp\bemang, now it runs properly. Also tried adding a space to the path, then BeamNG could not start. I interpret it as two separate issues:
1) BeamNG looks for a default userpath on the C: drive despite having automatically created one on the F: drive during installation.
2) Userpaths with spaces do not work.

**Comment by alessiogambi** [comment]
Commit e743813d45b508dbf732272c7637064fc61dae4f should have fixed the issue on setting user paths. The other issue about white spaces is pending at BeamNG.py
