### ISSUE TITLE
Time budget

### ISSUE THREAD

**Issue by ezecastellano** [se2p/tool-competition-av#51]
Would it be possible to know the order of magnitude of the time budget during the competition? Will it be minutes, hours, days? It would be useful to know that to determine which approach is more suitable. 

Thank you very much again.

**Comment by alessiogambi** [comment]
@ezecastellano We plan something in the order of (few) hours. We do not have a precise number at the moment, as the final decision very much depends on how many participants we'll have.  So I'll guess something in the range of 5-10hours. Less than 5 hours might not give the tools enough time to explore the space, while more than 10 hours becomes hard to manage on our side (each tool will be executed multiple times).

If you have a suggestion feel free to share it with us.

**Comment by ezecastellano** [comment]
Hi Alessio, thank you very much for the quick response. Knowing that is already very useful to us. 
Just to clarify, do you mean 5-10 hours of simulation time (--time-budget 5*60*60) or 5-10 hours of total execution? We noticed that the --time-budget does not actually count the time spent in generating the tests.

**Comment by p1ndsvin** [comment]
Hi @ezecastellano. Thank you for your suggestion. In the next commit, we will switch the budget from simulation time to total execution time. In this way, we will take into account also the time spent for test input generation.
