### ISSUE TITLE
Missing PyOpenGL-accelerate Dependency

### ISSUE THREAD

**Issue by ChristianBirchler** [se2p/tool-competition-av#54]
I am not sure if this is needed on all systems but I had to install also the `PyOpenGL-accelerate` module. Maybe this can be added to the `requirements-37.txt`.

**Comment by alessiogambi** [comment]
@ChristianBirchler Thanks, I'll add to the requirements-37.txt files.

**Comment by alessiogambi** [comment]
Sorry forgot to mention this has been address in 9c2c964dbd705eacdbc78e2f50733fae9237aeaf
