### ISSUE TITLE
Multi-threaded execution

### ISSUE THREAD

**Issue by ezecastellano** [se2p/tool-competition-av#56]
We understand that running multiple simulations in parallel is not possible. However, is there any other restriction on the number of threads we can use? For instance, is it possible to run a background thread while the simulator is running? 
Thanks again!

**Comment by alessiogambi** [comment]
@ezecastellano No, AFAIK there are no restrictions on using multiple threads. But pay attention that some libraries we use (e.g.,  BeamNGpy) are not thread-safe. If possible, may I ask you *why* do you need concurrency to implement the test generator?

**Comment by alessiogambi** [comment]
I close this for the moment.

**Comment by ezecastellano** [comment]
Sorry for the late reply. We were considering different options, and one of them could take advantage of using the simulation time for some background computations. Anyway, in the end, we are not going to use that idea.
