### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by alessiogambi** [se2p/tool-competition-av#6]
At the moment it only contains click for parsing the command line arguments

**Comment by alessiogambi** [comment]
Testing with Python 3.6.8 there's an issue with numpy, to solve it we need to enforce version 1.19.3
Also we need to include the requirements of the test generator as well.

**Comment by alessiogambi** [comment]
Shapely for Python 3.6 must be installed separately/manually. We need to provide the wheel file

**Comment by alessiogambi** [comment]
d3d4ae6ac1b72579f02414181da198161ffa4cd0 included the wheel file for shapely
ec4a03e53f966e224c70b17fa8617d0025b8fa1c updates the requirements for python 3.6 (and include Shapely as relative path)

**Comment by p1ndsvin** [comment]
[Installation guide](https://github.com/se2p/tool-competition-av/blob/main/documentation/INSTALL.md) contains info about how to install requirements and how to fetch the right Shapely wheel file

**Comment by p1ndsvin** [comment]
@alessiogambi should we remove the wheel file for Shapely from our repo and let the competitors download it from the website referenced in the installation guide?

**Comment by alessiogambi** [comment]
Sure.
