### ISSUE TITLE
OOB_percentage reporting

### ISSUE THREAD

**Issue by lorenzklampfl** [se2p/tool-competition-av#65]
Hello,
would it be possible to integrate in the code pipeline an oob_percentage reporting?  After execution of a test case, to either obtain the oob percentage value per state or the maximum percentage value, regardless if the executed test case passed or failed (similar to the reporting of the distance value within the execution data).

**Comment by alessiogambi** [comment]
@lorenzklampfl can you check if this pull request fits your need? #66 
The easiest thing was to report for each state the value of OOB_percentage. The updated code for OneTestGenerator shows how you can read those values out of the execution_data generated by the test, and select the max value.

**Comment by lorenzklampfl** [comment]
@alessiogambi thank you very much. The pull request perfectly fits our needs.

**Comment by alessiogambi** [comment]
Great. in this case, I'll go on and merge it to master

Thanks !
