### ISSUE TITLE
Sparseness measures

### ISSUE THREAD

**Issue by japeltom** [se2p/tool-competition-av#93]
In addition to finding a large number of failed roads, it would be desirable that the found rounds are variable. In 2021, a sparseness measure was introduced to measure variability. The drawback with this proposal is the usage of the maximum operator: a single test that is sufficiently different from other tests may skew the result to indicate variability while none is in fact present.

A simple fix is to drop the maximum operator and simply find the average.

A simple alternative would be to consider a road consisting of n points as a point in the 2n-dimensional Euclidean space and compute the average pairwise Euclidean distances of the failed roads. This approach also suffers from the above problem, so the median instead of an average could be reported.

Nevertheless, I think that whatever number is computed on the failed roads, it should be done on roads that are normalized in some sense. A simple first step would be to translate all roads to the origin and rotate them in such a way that line segment between the first two points makes an angle of 90 degrees with the x-axis. This way the comparison is both translation and rotation invariant.

**Comment by p1ndsvin** [comment]
Dear @japeltom,

We agree with you about the drawbacks introduced by the sparseness metric. Last year, we partially mitigated these drawbacks by considering a fixed-size portion of the road relevant to the failure. In this way, the diversity metric was independent of the roads' length. Moreover, we considered the weighted Levenshtein distance introduced in the DeepJanus paper, which is translation and rotation invariant.

This year, we will compare the test generators by using OOB_Coverage, a novel diversity metric based on our recent work DeepHyperion. We will identify fixed-size tests' portions relevant to the OOBs, extract their structural and behavioral features, and populate feature maps of a predefined size (i.e., 25x25 cells). Finally, we define `OOB_Coverage` by counting the cells in the map covered by the exposed OOBs.

OOB_Coverage is not a relative metric, like OOB sparseness; therefore, we believe it ensures a more fair comparison among the test generators despite the amount of OOBs that they found.

Please, let us know if we can provide further assistance and if this metric addresses your concerns, so we can close this issue.

**Comment by alessiogambi** [comment]
I close this issue for the moment. Feel free to reopen it.
